import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case zh
    case en

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .zh: return "中文"
        case .en: return "English"
        }
    }
}

enum AppText {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        if let value = table[language]?[key] {
            return value
        }
        if let fallback = table[.zh]?[key] {
            return fallback
        }
        return key
    }

    private static let table: [AppLanguage: [String: String]] = [
        .zh: [
            "tab.general": "通用",
            "tab.feishu": "飞书",
            "window.settings": "设置",
            "section.language": "语言",
            "language.label": "界面语言",
            "section.microphone": "麦克风",
            "microphone.input": "输入设备",
            "microphone.systemDefault": "跟随系统默认输入",
            "microphone.refresh": "刷新设备",
            "microphone.note": "会议软件里选择的麦克风不一定等于系统默认输入。这里指定后，录音会优先使用该设备。",
            "section.autoStop": "自动停止",
            "autoStop.enabled": "静音后自动停止",
            "autoStop.after": "%d 分钟双声道静音后停止",
            "autoStop.threshold": "静音阈值",
            "autoStop.note": "低于该音量视为静音。",
            "section.localStorage": "本地文件",
            "setting.retentionPolicy": "录音保留策略",
            "retention.keep": "一直保留",
            "retention.delete15": "上传成功 15 天后删除",
            "retention.delete30": "上传成功 30 天后删除",
            "retention.note": "只清理已生成飞书妙记链接的录音；未上传、上传失败或未完成的录音不会自动删除。",
            "section.cli": "命令行工具",
            "field.larkPath": "lark-cli 路径",
            "field.larkPathPrompt": "/opt/homebrew/bin/lark-cli 或 PATH",
            "cli.note": "留空时自动查找 Homebrew、npm 全局目录和 PATH。",
            "section.workflow": "工作流",
            "setting.autoUpload": "保存后自动上传",
            "setting.fetchNotes": "上传后拉取妙记",
            "field.recordingTitle": "录音标题",
            "field.recordingTitlePrompt": "例如：壳牌直播间项目汇报",
            "title.source.calendar": "来自日程",
            "title.source.manual": "手动命名",
            "section.afterUpload": "上传后",
            "setting.copyMinute": "上传后复制妙记链接",
            "setting.openMinute": "上传后打开妙记链接",
            "state.ready": "就绪",
            "state.audioIncomplete": "录音不完整",
            "state.uploading": "上传中",
            "state.uploaded": "已上传",
            "state.uploadFailed": "上传失败",
            "state.recording": "录制中",
            "state.paused": "已暂停",
            "action.recordMeeting": "录制会议",
            "action.record": "开始录制",
            "action.pause": "暂停",
            "action.resume": "继续",
            "action.stop": "停止",
            "action.uploadAnyway": "仍然上传",
            "action.openMinute": "打开妙记",
            "action.copyURL": "复制链接",
            "action.retryUpload": "重试上传",
            "action.uploadToFeishu": "上传到飞书",
            "action.copyMinuteURL": "复制妙记链接",
            "action.copyAudioFile": "复制音频文件",
            "action.copyTranscriptText": "复制逐字稿文本",
            "action.copyTranscriptFile": "复制逐字稿文件",
            "action.revealFinder": "在 Finder 中显示",
            "action.recordings": "录音文件",
            "action.settings": "设置…",
            "action.quit": "退出",
            "action.refresh": "刷新",
            "action.recordNoMeeting": "不关联会议，直接录制",
            "help.discard": "丢弃本次录音",
            "help.revealFolder": "显示录音文件夹",
            "help.openMinute": "打开飞书妙记",
            "help.copyMinute": "复制 minute_url",
            "help.refreshMeetings": "刷新会议",
            "help.recentActions": "更多操作",
            "help.dragRecent": "拖出录音文件，或使用右侧操作菜单",
            "help.recordThisMeeting": "录制这场会议",
            "help.openFolder": "打开 ~/Documents/Recorder1",
            "help.openPreferences": "打开设置",
            "text.uploadingFeishu": "正在上传到飞书妙记…",
            "text.meetings": "会议",
            "text.noMeetings": "附近没有会议。",
            "text.recent": "最近录音",
            "text.recordingFallback": "录音",
            "meter.desktop": "系统声音（左）",
            "meter.mic": "麦克风（右）",
            "recent.uploaded": "已上传",
            "recent.uploadFailed": "上传失败",
            "recent.audioReady": "音频已生成",
            "recent.rawOnly": "仅原始文件",
            "notice.meetingEndedTitle": "会议已结束，仍在录制",
            "notice.stopRecording": "停止录制",
            "notice.meetingEndedBody": "“%@”计划已结束。是否停止并保存？",
            "status.checkingMic": "正在检查麦克风权限…",
            "status.micPermissionRequired": "需要麦克风权限。请在系统设置中允许。",
            "status.desktopError": "系统声音错误：%@",
            "status.systemAudioSilent": "系统声音采集仍为静音。",
            "status.micError": "麦克风错误：%@",
            "status.createFolderFailed": "无法创建录音文件夹：%@",
            "status.captureStartFailed": "无法开始录音：%@",
            "status.mixing": "正在合成…",
            "status.savedSystemMissing": "已保存 %@ · 未录到系统声音",
            "status.saved": "已保存 %@",
            "status.savedAutoOff": "已保存 %@ · 自动上传已关闭",
            "status.mixFailed": "合成失败，原始文件已保留：%@",
            "status.discarded": "已丢弃",
            "status.noAudioToUpload": "没有可上传的 audio.m4a。",
            "status.uploadingFeishu": "正在上传到飞书…",
            "status.uploadedFeishu": "已上传到飞书妙记",
            "status.uploadFailed": "上传失败",
            "status.minuteCopied": "妙记链接已复制",
            "status.fileCopied": "已复制 %@",
            "status.fileReadFailed": "无法读取 %@",
            "status.textCopied": "已复制 %@ 的文本",
            "status.cleanupDeleted": "已清理 %d 个已上传的本地录音",
            "error.micFile": "无法打开麦克风文件：%@",
            "error.invalidMicFormat": "麦克风输入格式不可用。",
            "error.inputDeviceUnavailable": "选中的麦克风已不可用：%@",
            "error.setInputDeviceFailed": "无法使用选中的麦克风：%@（系统错误 %@）",
            "capture.degraded": "只录到麦克风，没有录到系统/会议远端声音，是否仍要上传？"
        ],
        .en: [
            "tab.general": "General",
            "tab.feishu": "Feishu",
            "window.settings": "Settings",
            "section.language": "Language",
            "language.label": "Interface language",
            "section.microphone": "Microphone",
            "microphone.input": "Input device",
            "microphone.systemDefault": "Use system default input",
            "microphone.refresh": "Refresh devices",
            "microphone.note": "The microphone selected in a meeting app may differ from macOS default input. If set here, recording uses this device first.",
            "section.autoStop": "Auto-stop",
            "autoStop.enabled": "Stop automatically after silence",
            "autoStop.after": "After %d min of silence on both channels",
            "autoStop.threshold": "Silence threshold",
            "autoStop.note": "A channel counts as silent below this level.",
            "section.localStorage": "Local files",
            "setting.retentionPolicy": "Recording retention",
            "retention.keep": "Keep forever",
            "retention.delete15": "Delete 15 days after upload",
            "retention.delete30": "Delete 30 days after upload",
            "retention.note": "Only recordings with a completed Feishu Minutes URL are cleaned up. Unuploaded, failed, or unfinished recordings are never deleted automatically.",
            "section.cli": "CLI",
            "field.larkPath": "lark-cli binary path",
            "field.larkPathPrompt": "/opt/homebrew/bin/lark-cli or PATH",
            "cli.note": "Leave blank to auto-detect Homebrew, npm global, and PATH locations.",
            "section.workflow": "Workflow",
            "setting.autoUpload": "Auto upload after save",
            "setting.fetchNotes": "Fetch notes after upload",
            "field.recordingTitle": "Recording title",
            "field.recordingTitlePrompt": "Example: Shell livestream project update",
            "title.source.calendar": "From calendar",
            "title.source.manual": "Manual title",
            "section.afterUpload": "After upload",
            "setting.copyMinute": "Copy minute_url after upload",
            "setting.openMinute": "Open minute_url after upload",
            "state.ready": "Ready",
            "state.audioIncomplete": "Audio incomplete",
            "state.uploading": "Uploading",
            "state.uploaded": "Uploaded",
            "state.uploadFailed": "Upload failed",
            "state.recording": "Recording",
            "state.paused": "Paused",
            "action.recordMeeting": "Record Meeting",
            "action.record": "Record",
            "action.pause": "Pause",
            "action.resume": "Resume",
            "action.stop": "Stop",
            "action.uploadAnyway": "Upload Anyway",
            "action.openMinute": "Open Minute",
            "action.copyURL": "Copy URL",
            "action.retryUpload": "Retry Upload",
            "action.uploadToFeishu": "Upload to Feishu",
            "action.copyMinuteURL": "Copy Minute URL",
            "action.copyAudioFile": "Copy audio file",
            "action.copyTranscriptText": "Copy transcript text",
            "action.copyTranscriptFile": "Copy transcript file",
            "action.revealFinder": "Reveal in Finder",
            "action.recordings": "Recordings",
            "action.settings": "Settings…",
            "action.quit": "Quit",
            "action.refresh": "Refresh",
            "action.recordNoMeeting": "Record without attaching to a meeting",
            "help.discard": "Discard this recording",
            "help.revealFolder": "Reveal recording folder",
            "help.openMinute": "Open Feishu Minutes",
            "help.copyMinute": "Copy minute_url",
            "help.refreshMeetings": "Refresh meetings",
            "help.recentActions": "Actions",
            "help.dragRecent": "Drag the recording artifact out, or use the actions menu",
            "help.recordThisMeeting": "Record this meeting",
            "help.openFolder": "Open ~/Documents/Recorder1",
            "help.openPreferences": "Open Preferences",
            "text.uploadingFeishu": "Uploading to Feishu Minutes...",
            "text.meetings": "Meetings",
            "text.noMeetings": "No meetings nearby.",
            "text.recent": "Recent recordings",
            "text.recordingFallback": "Recording",
            "meter.desktop": "Desktop (L)",
            "meter.mic": "Mic (R)",
            "recent.uploaded": "Uploaded",
            "recent.uploadFailed": "Upload failed",
            "recent.audioReady": "Audio ready",
            "recent.rawOnly": "Raw only",
            "notice.meetingEndedTitle": "Meeting ended — still recording",
            "notice.stopRecording": "Stop Recording",
            "notice.meetingEndedBody": "%@ was scheduled to end. Stop and save?",
            "status.checkingMic": "Checking microphone permission...",
            "status.micPermissionRequired": "Microphone permission is required. Allow it in System Settings.",
            "status.desktopError": "Desktop audio error: %@",
            "status.systemAudioSilent": "System audio capture is silent.",
            "status.micError": "Mic error: %@",
            "status.createFolderFailed": "Could not create recording folder: %@",
            "status.captureStartFailed": "Could not start capture: %@",
            "status.mixing": "Mixing…",
            "status.savedSystemMissing": "Saved %@ · system audio missing",
            "status.saved": "Saved %@",
            "status.savedAutoOff": "Saved %@ · auto upload off",
            "status.mixFailed": "Mix failed (raw files kept): %@",
            "status.discarded": "Discarded",
            "status.noAudioToUpload": "No saved audio.m4a to upload.",
            "status.uploadingFeishu": "Uploading to Feishu...",
            "status.uploadedFeishu": "Uploaded to Feishu Minutes",
            "status.uploadFailed": "Upload failed",
            "status.minuteCopied": "Minute URL copied",
            "status.fileCopied": "Copied %@",
            "status.fileReadFailed": "Could not read %@",
            "status.textCopied": "Copied text of %@",
            "status.cleanupDeleted": "Cleaned up %d uploaded local recordings",
            "error.micFile": "Could not open mic file: %@",
            "error.invalidMicFormat": "Microphone input format is unusable.",
            "error.inputDeviceUnavailable": "Selected microphone is no longer available: %@",
            "error.setInputDeviceFailed": "Could not use selected microphone: %@ (OSStatus %@)",
            "capture.degraded": "Only microphone was captured; system/remote meeting audio is missing. Upload anyway?"
        ]
    ]
}
